//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electronic_Archive.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Annul
    {
        public int ID_annul { get; set; }
        public string ДН { get; set; }
        public string Замены { get; set; }
        public string Комментарий { get; set; }
        public string Дата { get; set; }
        public string Карточка { get; set; }
        public string Копии { get; set; }
        public string Применяемость { get; set; }
        public string Изменения { get; set; }
    }
}
