//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electronic_Archive.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cards
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cards()
        {
            this.Changes = new HashSet<Changes>();
            this.Copies = new HashSet<Copies>();
            this.Exploitation = new HashSet<Exploitation>();
        }
    
        public string ДН { get; set; }
        public string Название { get; set; }
        public Nullable<long> Подразделение { get; set; }
        public string Вид_документа { get; set; }
        public string Знак_заказчика { get; set; }
        public string Номер_решения { get; set; }
        public Nullable<int> A0 { get; set; }
        public Nullable<int> A1 { get; set; }
        public Nullable<int> A2 { get; set; }
        public Nullable<int> A3 { get; set; }
        public Nullable<int> A4 { get; set; }
        public string Другое { get; set; }
        public Nullable<long> Количество { get; set; }
        public string Подлинник { get; set; }
        public string Дубликат { get; set; }
        public Nullable<long> ИН_подлинник { get; set; }
        public Nullable<long> ИН_дубликат { get; set; }
        public string Дата_подлинник { get; set; }
        public string Дата_дубликат { get; set; }
        public string Литера { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Changes> Changes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Copies> Copies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exploitation> Exploitation { get; set; }
    }
}
