//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electronic_Archive.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Changes
    {
        public int ID_changes { get; set; }
        public string ДН { get; set; }
        public Nullable<double> Номер_извещения { get; set; }
        public string Дата { get; set; }
        public string Изменения { get; set; }
        public string Литера { get; set; }
    
        public virtual Cards Cards { get; set; }
    }
}
