//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electronic_Archive.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Copies
    {
        public int ID_copies { get; set; }
        public string ДН { get; set; }
        public string Дата { get; set; }
        public string Наряд { get; set; }
        public string Абонент { get; set; }
        public Nullable<long> Поступило { get; set; }
        public Nullable<long> Списано { get; set; }
    
        public virtual Cards Cards { get; set; }
    }
}
