//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electronic_Archive.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArchiveEntities : DbContext
    {
        public ArchiveEntities()
            : base("name=ArchiveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Annul> Annul { get; set; }
        public virtual DbSet<Cards> Cards { get; set; }
        public virtual DbSet<CardsLog> CardsLog { get; set; }
        public virtual DbSet<Changes> Changes { get; set; }
        public virtual DbSet<Copies> Copies { get; set; }
        public virtual DbSet<Exploitation> Exploitation { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
